---
# This playbook deploys the whole application stack in this site.

- name: Cleanup Cloud-init
  hosts: all
  become: yes
  become_user: root
  remote_user: root
  tags: cleanup
  gather_facts: yes

  roles:
    - cleanup

- name: Deploy common configuration
  hosts: all
  remote_user: root
  tags: common
  gather_facts: yes

  tasks:
    - include_role: name=firewalld
    - include_role: name=ntp
    - include_role: name=minimal

- name: Rebooting host
  hosts: all
  become: no
  remote_user: vagrant
  gather_facts: yes

  roles:
    - reboot
