---
# This playbook deploys the whole application stack in this site.

- import_playbook: common.yml

- name: Installing and configuring PXE Server
  hosts: all
  remote_user: root
  tags: pxe_setup
  gather_facts: yes

  roles:
   - pxe-server
   - reboot
