---

- name: Installing dnf package
  yum: name=dnf state=present
  when: ( ansible_facts['distribution'] == 'CentOS' or ansible_facts['distribution'] == 'OracleLinux' ) and ansible_facts['distribution_major_version'] == '8'

- name: Removing Cloud-Init package...
  dnf: name=cloud-init state=absent

- name: Removing cloud-init user...
  user:
    name: cloud-user
    state: absent

- name: Removing cloud-init directory...
  file:
    path: /home/cloud-user/
    state: absent
