---

- name: Installing Apache
  dnf: 
   name: ['httpd','mod_ssl','mod_fcgid']
   state: present
  ignore_errors: False

- name: Coping HTTP configuration files
  template: src={{ item }} dest=/etc/httpd/conf.d/{{ item | basename | regex_replace('\.j2','') }} force=yes
  with_items:
   - http.conf.j2

- name: Adding configuration to HTTPs configuration files...
  lineinfile:
    dest: /etc/httpd/conf.d/ssl.conf
    line: "{{ http_ssl_conf }}"
    insertbefore: '\<\/VirtualHost\>'
    state: present

- name: Regexp HTTP config...
  replace:
   path: /etc/httpd/conf/httpd.conf
   regexp: '(AllowOverride)(\s.*)?'
   replace: '\1 All'

- name: Enable service Apache2
  service: name=httpd state=started enabled=yes
  notify: restart apache

- name: Opening HTTP firewall port
  firewalld:
   service: http
   zone: public
   permanent: true
   state: enabled
   immediate: yes
  ignore_errors: true

#- name: Opening HTTPs firewall port
#  firewalld:
#   service: https
#   zone: public
#   permanent: true
#   state: enabled
#   immediate: yes
#  ignore_errors: true

